global:
  namespace: argo-events

workflow:
  ttlSecondsAfterFinished: 300

sensor:
  dependencies:
  - eventSourceName: webhook
    parameters:
    - dest: spec.arguments.parameters.0.value
      src:
        dataKey: body.message
    - dest: spec.arguments.parameters.1.value
      src:
        dataKey: body.delay
  - eventSourceName: file   
    parameters:
    - src:
        dataKey: name
      dest: spec.arguments.parameters.0.value 
  - eventSourceName: calendar
    parameters:
      - src:
          dataKey: metadata.message
        dest: spec.arguments.parameters.0.value
      - src:
          dataKey: metadata.delay
        dest: spec.arguments.parameters.1.value
