apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    example:
      endpoint: /example
      method: POST
      port: "12000"
      url: ""

---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: file
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /test-data
          name: demo-volume
    volumes:
      - name: demo-volume
        persistentVolumeClaim:
          claimName: demo-pvc
  file:
    example:
      watchPathConfig:
        # directory to watch
        directory: /test-data/
        # path to watch
        path: file.txt
      # supported types are: CREATE, WRITE, REMOVE, RENAME, CHMOD
      eventType: CREATE

---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  calendar:
    example:
      interval: 30m
      metadata:
        message: "hello MM"
        delay: "15"
