apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  volumes:
    - name: demo-volume
      persistentVolumeClaim:
        claimName: demo-pvc
  containers:
    - name: main
      image: ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: "/test-data"
          name: demo-volume
