apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: mycontainer
      image: ubuntu
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: "/test-data"
          name: my-volume
