apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
