apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  ttlSecondsAfterFinished: {{ .Values.workflow.ttlSecondsAfterFinished }}
  entrypoint: database-setup
  arguments:
    parameters:
      - name: message
        value: hello world
      - name: delay
        value: "10"
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{`{{inputs.parameters.message}}`}}"]
    - name: idle
      container:
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args:
        - "echo {{`{{workflow.parameters.delay}}`}} && sleep {{`{{workflow.parameters.delay}}`}}"
    - name: database-setup
      dag:
        tasks:
          - name: "database-export"
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{`{{workflow.parameters.message}}`}}"
          - name: "database1-import"
            dependencies: ["database-export"]
            template: idle
          - name: "database2-import"
            dependencies: ["database-export"]
            template: idle
