apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
  namespace: {{ template "helper.NAMESPACE" .}}
spec:
  ttlSecondsAfterFinished: {{ .Values.workflow.ttlSecondsAfterFinished }}
  entrypoint: triangle
  arguments:
    parameters:
      - name: message
        value: hello world
      - name: delay
        value: "10"
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{`{{inputs.parameters.message}}`}}"]
    - name: idle
      container:
        image: ubuntu
        command: ["/bin/bash", "-c"]
        args:
        - "echo {{`{{workflow.parameters.delay}}`}} && sleep {{`{{workflow.parameters.delay}}`}}"
    - name: triangle
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters:
                - name: message
                  value: "{{`{{workflow.parameters.message}}`}}"
          - name: B
            dependencies: [A]
            template: idle
          - name: C
            dependencies: [A]
            template: idle
